name: Deployment to EC2 Instance
on: 
  workflow_run:
    workflows: ["Build and Push Docker Image to Registry"]
    types: [completed]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull Docker Image
        run: |
          docker pull imanyauma/ntx-devops-test:latest
      - name: Clean Up Docker Container
        if: always()
        run: |
          docker stop ntx-devops-test
          docker rm ntx-devops-test
      - name: Run Docker Container
        run: |
          docker run --name ntx-devops-test -d -p 3000:3000 imanyauma/ntx-devops-test:latest
      - name: Verify Container is Running
        run: |
          docker ps | grep ntx-devops-test
